# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devnews < Formula
  desc "TUI engineering blog aggregator"
  homepage "https://github.com/matheuskafuri/devnews"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matheuskafuri/devnews/releases/download/v0.2.0/devnews_0.2.0_darwin_amd64.tar.gz"
      sha256 "5133c3c86733840047fc1a516dcb08b41133a81bbcf0f6eae6b1da235049d364"

      define_method(:install) do
        bin.install "devnews"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matheuskafuri/devnews/releases/download/v0.2.0/devnews_0.2.0_darwin_arm64.tar.gz"
      sha256 "a913a951239ac5c42bef506d4544e9363aab37f38a5a20de82c87863eb728f9e"

      define_method(:install) do
        bin.install "devnews"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/matheuskafuri/devnews/releases/download/v0.2.0/devnews_0.2.0_linux_amd64.tar.gz"
      sha256 "4292f0c0317f852191ee0812425f81b5415d466de95c2199c09a10bbd9dac658"
      define_method(:install) do
        bin.install "devnews"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matheuskafuri/devnews/releases/download/v0.2.0/devnews_0.2.0_linux_arm64.tar.gz"
      sha256 "b67233f8064268a011ef942f7483014bb98c7a080ac2d5746ff5749c9458cc35"
      define_method(:install) do
        bin.install "devnews"
      end
    end
  end

  test do
    system "#{bin}/devnews", "version"
  end
end
