# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devnews < Formula
  desc "TUI engineering blog aggregator"
  homepage "https://github.com/matheuskafuri/devnews"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matheuskafuri/devnews/releases/download/v0.4.1/devnews_0.4.1_darwin_amd64.tar.gz"
      sha256 "64bb32ef544fa53fdff42b4462335c7bf9b0a10a3997ab601aacf80c913ec9a7"

      define_method(:install) do
        bin.install "devnews"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matheuskafuri/devnews/releases/download/v0.4.1/devnews_0.4.1_darwin_arm64.tar.gz"
      sha256 "e560060e9dc6d35d3c612ddaeb4e428a33716dd796469ed90bbec57c2b2a5633"

      define_method(:install) do
        bin.install "devnews"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/matheuskafuri/devnews/releases/download/v0.4.1/devnews_0.4.1_linux_amd64.tar.gz"
      sha256 "0800506502b567c4ad024f3315e8da79bb90fc7b293c1d56b728e97f3ed39809"
      define_method(:install) do
        bin.install "devnews"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matheuskafuri/devnews/releases/download/v0.4.1/devnews_0.4.1_linux_arm64.tar.gz"
      sha256 "e76ffb7558a74eee592001bda3c9ba95c97071da9f3795478478c9729d1c9f1a"
      define_method(:install) do
        bin.install "devnews"
      end
    end
  end

  test do
    system "#{bin}/devnews", "version"
  end
end
