# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devnews < Formula
  desc "TUI engineering blog aggregator"
  homepage "https://github.com/matheuskafuri/devnews"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matheuskafuri/devnews/releases/download/v0.5.0/devnews_0.5.0_darwin_amd64.tar.gz"
      sha256 "e927b85b43da265d233783aff94e6f8cd75cfe767269845b3c76bc3cc38cb4be"

      define_method(:install) do
        bin.install "devnews"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matheuskafuri/devnews/releases/download/v0.5.0/devnews_0.5.0_darwin_arm64.tar.gz"
      sha256 "b5b4612bcab5348ab6cb469b1368883f19818cc6e681a5d1b67362b0368eb316"

      define_method(:install) do
        bin.install "devnews"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/matheuskafuri/devnews/releases/download/v0.5.0/devnews_0.5.0_linux_amd64.tar.gz"
      sha256 "0fa2682d5696e865271eee4a39540d01811a0b3ef60e710616b29c0e11832fe9"
      define_method(:install) do
        bin.install "devnews"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matheuskafuri/devnews/releases/download/v0.5.0/devnews_0.5.0_linux_arm64.tar.gz"
      sha256 "ea51c2591e3f8af2c89f54a0835cb4a1024169e61c931c864028888bccbcf469"
      define_method(:install) do
        bin.install "devnews"
      end
    end
  end

  test do
    system "#{bin}/devnews", "version"
  end
end
